"""
Drift Code Generator — Walks the AST and emits Python source code.

Pipeline: source → tokens → AST → [CODEGEN] → Python

This is a deterministic, mechanical translation. No AI involved.
The same .drift input ALWAYS produces the same .py output.
"""

import re
from . import ast_nodes as ast


# Map Drift types to Python/Pydantic types
TYPE_MAP = {
    'string': 'str',
    'number': 'float',
    'bool': 'bool',
    'document': 'str',
    'currency': 'float',
    'duration': 'float',
    'timestamp': 'str',
}

# Map currency symbols to ISO codes
CURRENCY_MAP = {'£': 'GBP', '$': 'USD', '€': 'EUR'}


class CodeGenerator:
    def __init__(self):
        self.indent_level = 0
        self.lines: list[str] = []
        self.schemas_declared: list[str] = []

    def generate(self, program: ast.Program) -> str:
        """Generate complete Python source from a Drift program."""
        self.emit_header()
        self.emit_line("")

        # First pass: collect all schema names
        for decl in program.declarations:
            if isinstance(decl, ast.SchemaDecl):
                self.schemas_declared.append(decl.name)

        # Generate declarations in order
        for decl in program.declarations:
            if isinstance(decl, ast.ConfigDecl):
                self.gen_config(decl)
            elif isinstance(decl, ast.SchemaDecl):
                self.gen_schema(decl)
            elif isinstance(decl, ast.AgentDecl):
                self.gen_agent(decl)
            self.emit_line("")

        return '\n'.join(self.lines)

    # ─── Output Helpers ────────────────────────────────────────────

    def emit_line(self, text: str = ""):
        if text:
            self.lines.append("    " * self.indent_level + text)
        else:
            self.lines.append("")

    def emit_lines(self, *texts):
        for t in texts:
            self.emit_line(t)

    def indent(self):
        self.indent_level += 1

    def dedent(self):
        self.indent_level -= 1

    # ─── Header ────────────────────────────────────────────────────

    def emit_header(self):
        self.emit_lines(
            '"""',
            'Auto-generated by Drift v0.1 — do not edit by hand.',
            'Source: <drift_file>',
            '"""',
            '',
            'import asyncio',
            'from typing import Optional, Literal',
            'from dataclasses import dataclass, field',
            '',
            '# Drift runtime imports',
            'from drift.runtime import (',
            '    Agent, step_decorator, Budget, ModelRouter, Intent,',
            '    CostTracker, Checkpoint, Confident, run_agent,',
            '    DriftError, StepFailed, SchemaViolation, BudgetExceeded,',
            '    ModelUnavailable, RateLimited, AuthError,',
            ')',
        )

    # ─── Config ────────────────────────────────────────────────────

    def gen_config(self, config: ast.ConfigDecl):
        self.emit_line("# ── Config ──")
        self.emit_line(f"DRIFT_CONFIG = {{")
        self.indent()
        for k, v in config.entries.items():
            self.emit_line(f'"{k}": "{v}",')
        self.dedent()
        self.emit_line("}")

    # ─── Schema ────────────────────────────────────────────────────

    def gen_schema(self, schema: ast.SchemaDecl):
        self.emit_line(f"# ── Schema: {schema.name} ──")
        self.emit_line("")
        self.emit_line(f"@dataclass")
        self.emit_line(f"class {schema.name}:")
        self.indent()

        if not schema.fields:
            self.emit_line("pass")
        else:
            # Generate docstring with field descriptions
            self.emit_line(f'"""Drift schema: {schema.name}"""')
            for f in schema.fields:
                py_type = self.gen_type(f.type_expr)
                if f.optional:
                    py_type = f"Optional[{py_type}]"

                default = " = None" if f.optional else ""

                # Add constraint comments
                constraint_comment = ""
                for c in f.constraints:
                    if isinstance(c, ast.BetweenConstraint):
                        constraint_comment = f"  # valid range: {c.low} to {c.high}"

                self.emit_line(f"{f.name}: {py_type}{default}{constraint_comment}")

            # Generate validation method
            has_constraints = any(f.constraints for f in schema.fields)
            if has_constraints:
                self.emit_line("")
                self.emit_line("def validate(self):")
                self.indent()
                self.emit_line('"""Validate field constraints."""')
                for f in schema.fields:
                    for c in f.constraints:
                        if isinstance(c, ast.BetweenConstraint):
                            self.emit_line(f"if self.{f.name} is not None:")
                            self.indent()
                            self.emit_line(f"assert {c.low} <= self.{f.name} <= {c.high}, \\")
                            self.emit_line(f'    f"{f.name} must be between {c.low} and {c.high}, got {{self.{f.name}}}"')
                            self.dedent()
                self.emit_line("return self")
                self.dedent()

        self.dedent()

    def gen_type(self, type_expr) -> str:
        if type_expr is None:
            return "str"

        if isinstance(type_expr, ast.ListType):
            if type_expr.element_type:
                inner = self.gen_type(type_expr.element_type)
                return f"list[{inner}]"
            return "list"

        if isinstance(type_expr, ast.MapType):
            k = self.gen_type(type_expr.key_type) if type_expr.key_type else "str"
            v = self.gen_type(type_expr.value_type) if type_expr.value_type else "str"
            return f"dict[{k}, {v}]"

        if isinstance(type_expr, ast.ConfidentType):
            # The inner type is documentation; the runtime stores Any.
            # Codegen emits the bare runtime class so isinstance checks work
            # and `.value`/`.confidence` attribute access compiles cleanly.
            return "Confident"

        if isinstance(type_expr, ast.EnumType):
            vals = ", ".join(f'"{v}"' for v in type_expr.values)
            return f"Literal[{vals}]"

        if isinstance(type_expr, ast.TypeExpr):
            return TYPE_MAP.get(type_expr.name, type_expr.name)

        return "str"

    # ─── Agent ─────────────────────────────────────────────────────

    def gen_agent(self, agent: ast.AgentDecl):
        self.emit_line(f"# ── Agent: {agent.name} ──")
        self.emit_line("")
        self.emit_line(f"class {agent.name}(Agent):")
        self.indent()
        self.emit_line(f'"""Drift agent: {agent.name}"""')
        self.emit_line("")

        # Collect step names for self-call detection
        self._agent_step_names = {s.name for s in agent.steps}

        # __init__
        self.emit_line("def __init__(self):")
        self.indent()

        # Model config
        model_args = self.gen_model_init(agent.model_config)
        self.emit_line(f"model = {model_args}")

        # Budget config
        budget_args = self.gen_budget_init(agent.budget_config)
        self.emit_line(f"budget = {budget_args}")

        # Quality config
        quality = 0.85
        if agent.quality_config:
            quality = agent.quality_config.min_confidence

        self.emit_line("")
        self.emit_line(f"super().__init__(")
        self.indent()
        self.emit_line(f'name="{agent.name}",')
        self.emit_line(f'model=model,')
        self.emit_line(f'budget=budget,')
        self.emit_line(f'min_confidence={quality},')
        self.dedent()
        self.emit_line(")")
        self.dedent()

        # Steps
        for s in agent.steps:
            self.emit_line("")
            self.gen_step(s)

        self.dedent()

    def gen_model_init(self, config) -> str:
        if config is None:
            return 'ModelRouter(default="claude-sonnet")'

        parts = []
        if config.default:
            parts.append(f'default="{config.default}"')
        if config.prefer and config.prefer != config.default:
            parts.append(f'prefer="{config.prefer}"')
        if config.fallback:
            parts.append(f'fallback=["{config.fallback}"]')
        if config.never:
            parts.append(f'never=["{config.never}"]')

        return f"ModelRouter({', '.join(parts)})"

    def gen_budget_init(self, config) -> str:
        if config is None:
            return 'Budget(max_per_run=10.0, currency="USD")'

        currency = CURRENCY_MAP.get(config.currency_sym, 'USD')
        return f'Budget(max_per_run={config.value}, currency="{currency}")'

    # ─── Step ──────────────────────────────────────────────────────

    def gen_step(self, step: ast.StepDecl):
        # Decorator
        ret_schema = "None"
        if step.return_type:
            ret_schema = self.gen_type(step.return_type)

        modifier_args = ""
        if step.modifier:
            modifier_args = f', modifier="{step.modifier}"'

        self.emit_line(f"@step_decorator(output={ret_schema}{modifier_args})")

        # Method signature
        params = ["self"]
        for p in step.params:
            py_type = self.gen_type(p.type_expr)
            params.append(f"{p.name}: {py_type}")

        param_str = ", ".join(params)
        ret_annotation = ""
        if step.return_type:
            ret_annotation = f" -> {ret_schema}"

        self.emit_line(f"async def {step.name}({param_str}){ret_annotation}:")
        self.indent()

        # Step body
        if not step.body:
            self.emit_line("pass")
        else:
            # Budget pre-check
            self.emit_line("# Budget pre-check")
            self.emit_line("self.cost_tracker.pre_check()")
            self.emit_line("")

            for i, stmt in enumerate(step.body):
                is_last = (i == len(step.body) - 1)
                # If last statement is an intent expr without explicit return, add one
                if (is_last and step.return_type and
                    isinstance(stmt, ast.ExprStmt) and
                    isinstance(stmt.expr, ast.IntentExpr)):
                    expr_code = self.gen_expr(stmt.expr)
                    self.emit_line(f"_result = {expr_code}")
                    self.emit_line(f"self.checkpoint.save('{step.name}', _result)")
                    self.emit_line("return _result")
                else:
                    self.gen_statement(stmt)

        self.dedent()

    # ─── Statements ────────────────────────────────────────────────

    def gen_statement(self, stmt):
        if isinstance(stmt, ast.LetStmt):
            self.gen_let(stmt)
        elif isinstance(stmt, ast.ReturnStmt):
            self.gen_return(stmt)
        elif isinstance(stmt, ast.RespondStmt):
            self.gen_respond(stmt)
        elif isinstance(stmt, ast.IfStmt):
            self.gen_if(stmt)
        elif isinstance(stmt, ast.ForEachStmt):
            self.gen_for_each(stmt)
        elif isinstance(stmt, ast.MatchStmt):
            self.gen_match(stmt)
        elif isinstance(stmt, ast.AttemptStmt):
            self.gen_attempt(stmt)
        elif isinstance(stmt, ast.RetryStmt):
            self.emit_line("continue  # retry the attempt block")
        elif isinstance(stmt, ast.FailStmt):
            self.gen_fail(stmt)
        elif isinstance(stmt, ast.ExprStmt):
            expr_code = self.gen_expr(stmt.expr)
            if 'await' in expr_code:
                self.emit_line(expr_code)
            else:
                self.emit_line(expr_code)

    def gen_let(self, stmt: ast.LetStmt):
        expr = self.gen_expr(stmt.value)
        if 'await' in expr:
            self.emit_line(f"{stmt.name} = {expr}")
        else:
            self.emit_line(f"{stmt.name} = {expr}")

    def gen_return(self, stmt: ast.ReturnStmt):
        if stmt.value is None:
            self.emit_line("return")
        else:
            expr = self.gen_expr(stmt.value)
            # Checkpoint before return
            self.emit_line(f"_result = {expr}")
            self.emit_line(f"self.checkpoint.save('{self._current_step_name()}', _result)")
            self.emit_line("return _result")

    def _current_step_name(self):
        # Walk back up the lines to find the step name — simple heuristic
        for line in reversed(self.lines):
            if 'async def ' in line:
                match = re.search(r'async def (\w+)', line)
                if match:
                    return match.group(1)
        return "unknown"

    def gen_respond(self, stmt: ast.RespondStmt):
        expr = self.gen_expr(stmt.value)
        self.emit_line(f"self.output({expr})")

    def gen_if(self, stmt: ast.IfStmt):
        cond = self.gen_expr(stmt.condition)
        self.emit_line(f"if {cond}:")
        self.indent()
        for s in stmt.body:
            self.gen_statement(s)
        if not stmt.body:
            self.emit_line("pass")
        self.dedent()

        if stmt.otherwise_if:
            self.emit_line("elif " + self.gen_expr(stmt.otherwise_if.condition) + ":")
            self.indent()
            for s in stmt.otherwise_if.body:
                self.gen_statement(s)
            self.dedent()
            # Handle chained otherwise-ifs
            if stmt.otherwise_if.otherwise_body:
                self.emit_line("else:")
                self.indent()
                for s in stmt.otherwise_if.otherwise_body:
                    self.gen_statement(s)
                self.dedent()
        elif stmt.otherwise_body:
            self.emit_line("else:")
            self.indent()
            for s in stmt.otherwise_body:
                self.gen_statement(s)
            self.dedent()

    def gen_for_each(self, stmt: ast.ForEachStmt):
        iterable = self.gen_expr(stmt.iterable)
        if stmt.parallel:
            self.emit_line(f"# Parallel fan-out (concurrent execution)")
            self.emit_line(f"async def _task({stmt.var_name}):")
            self.indent()
            for s in stmt.body:
                self.gen_statement(s)
            self.dedent()
            self.emit_line(f"await asyncio.gather(*[_task(item) for item in {iterable}])")
        else:
            self.emit_line(f"for {stmt.var_name} in {iterable}:")
            self.indent()
            for s in stmt.body:
                self.gen_statement(s)
            if not stmt.body:
                self.emit_line("pass")
            self.dedent()

    def gen_attempt(self, stmt: ast.AttemptStmt):
        """attempt { body } recover from { ErrorType -> handler ... }

        Compiles to a bounded retry loop wrapping try/except. Inside an arm,
        `retry` becomes `continue` (next iteration). Falling through the arm
        without `retry` breaks out — recovery succeeded. If the loop runs
        all iterations without breaking, we raise StepFailed.
        """
        self.emit_line(f"# attempt/recover (max {stmt.max_retries} retries)")
        self.emit_line(f"for _attempt in range({stmt.max_retries}):")
        self.indent()
        self.emit_line("try:")
        self.indent()
        if not stmt.body:
            self.emit_line("pass")
        last_terminal = False
        for s in stmt.body:
            self.gen_statement(s)
            if isinstance(s, (ast.ReturnStmt, ast.FailStmt)):
                last_terminal = True
        # If the try body didn't end in return/fail, emit a `break` so a
        # successful attempt exits the retry loop.
        if not last_terminal:
            self.emit_line("break")
        self.dedent()
        # Emit except arms. `any error` last because Python evaluates them
        # in order and DriftError would shadow specific subclasses.
        specific = [a for a in stmt.arms if not a.is_default]
        default_arm = next((a for a in stmt.arms if a.is_default), None)
        for arm in specific:
            self.emit_line(f"except {arm.error_type} as _err:")
            self.indent()
            self._gen_recover_body(arm)
            self.dedent()
        if default_arm:
            self.emit_line("except DriftError as _err:")
            self.indent()
            self._gen_recover_body(default_arm)
            self.dedent()
        self.dedent()
        # If we ran all retries without breaking, raise so the caller knows.
        self.emit_line("else:")
        self.indent()
        self.emit_line(
            f'raise StepFailed("attempt block exhausted {stmt.max_retries} retries")'
        )
        self.dedent()

    def _gen_recover_body(self, arm: ast.RecoverArm):
        if not arm.body:
            # Bare arm with no statements — re-raise so the failure is visible.
            self.emit_line("raise")
            return
        # Detect a bare `retry` so we know whether to add a fallthrough raise.
        had_terminal = False
        for s in arm.body:
            self.gen_statement(s)
            if isinstance(s, (ast.RetryStmt, ast.ReturnStmt, ast.FailStmt)):
                had_terminal = True
        if not had_terminal:
            # Recovered without retry/return/fail — break out of the loop
            # so the attempt doesn't run again.
            self.emit_line("break")

    def gen_fail(self, stmt: ast.FailStmt):
        msg = self.gen_expr(stmt.message) if stmt.message else '"step failed"'
        self.emit_line(f"raise StepFailed({msg})")

    def gen_match(self, stmt: ast.MatchStmt):
        target = self.gen_expr(stmt.target)
        first = True
        for arm in stmt.arms:
            if arm.is_default:
                self.emit_line("else:")
            elif first:
                pattern = self.gen_expr(arm.pattern)
                self.emit_line(f"if {target} == {pattern}:")
                first = False
            else:
                pattern = self.gen_expr(arm.pattern)
                self.emit_line(f"elif {target} == {pattern}:")

            self.indent()
            for s in arm.body:
                self.gen_statement(s)
            if not arm.body:
                self.emit_line("pass")
            self.dedent()

    # ─── Expressions ───────────────────────────────────────────────

    def gen_expr(self, expr) -> str:
        if isinstance(expr, ast.IntentExpr):
            return self.gen_intent(expr)
        elif isinstance(expr, ast.FnCall):
            return self.gen_fn_call(expr)
        elif isinstance(expr, ast.FieldAccess):
            return f"{self.gen_expr(expr.target)}.{expr.field_name}"
        elif isinstance(expr, ast.BinOp):
            return self.gen_binop(expr)
        elif isinstance(expr, ast.UnaryOp):
            op = expr.op
            if op == 'not':
                return f"not {self.gen_expr(expr.operand)}"
            return f"({op}{self.gen_expr(expr.operand)})"
        elif isinstance(expr, ast.Ident):
            return expr.name
        elif isinstance(expr, ast.StringLit):
            if expr.has_interpolation:
                return f'f"{expr.value}"'
            return f'"{expr.value}"'
        elif isinstance(expr, ast.NumberLit):
            if expr.value == int(expr.value):
                return str(int(expr.value))
            return str(expr.value)
        elif isinstance(expr, ast.CurrencyLit):
            return str(expr.value)
        elif isinstance(expr, ast.DurationLit):
            seconds_map = {'s': 1, 'm': 60, 'h': 3600, 'd': 86400}
            seconds = expr.value * seconds_map.get(expr.unit, 1)
            return str(seconds)
        elif isinstance(expr, ast.BoolLit):
            return "True" if expr.value else "False"
        elif isinstance(expr, ast.ListLit):
            elems = ", ".join(self.gen_expr(e) for e in expr.elements)
            return f"[{elems}]"
        elif isinstance(expr, ast.SchemaConstructor):
            fields = ", ".join(
                f"{k}={self.gen_expr(v)}" for k, v in expr.fields.items()
            )
            return f"{expr.type_name}({fields})"
        elif isinstance(expr, ast.PipeExpr):
            return self.gen_pipe(expr)
        elif expr is None:
            return "None"
        else:
            return repr(expr)

    def gen_binop(self, expr: ast.BinOp) -> str:
        op = expr.op
        # Special-case `is confident` / `is uncertain` BEFORE evaluating the
        # right-hand side, because `confident` and `uncertain` are bare
        # identifiers in the source — we don't want them treated as variable
        # references in the generated code.
        if op == 'is' and isinstance(expr.right, ast.Ident):
            left = self.gen_expr(expr.left)
            kw = expr.right.name
            if kw == 'confident':
                return f"({left}.is_confident(self.min_confidence))"
            if kw == 'uncertain':
                return f"(not {left}.is_confident(self.min_confidence))"
        left = self.gen_expr(expr.left)
        right = self.gen_expr(expr.right)
        if op == 'and':
            return f"({left} and {right})"
        elif op == 'or':
            return f"({left} or {right})"
        elif op == 'is':
            return f"({left} == {right})"
        elif op == 'not in':
            return f"({left} not in {right})"
        else:
            return f"({left} {op} {right})"

    def gen_fn_call(self, call: ast.FnCall) -> str:
        args_parts = []
        for a in call.args:
            if isinstance(a, tuple):
                # Named argument
                args_parts.append(f"{a[0]}={self.gen_expr(a[1])}")
            else:
                args_parts.append(self.gen_expr(a))
        args_str = ", ".join(args_parts)

        if call.target:
            target = self.gen_expr(call.target)
            # Translate .add() to .append() for Python lists
            method = call.name
            if method == 'add':
                method = 'append'
            return f"{target}.{method}({args_str})"

        # Check if this is an internal step call
        step_names = getattr(self, '_agent_step_names', set())
        if call.name in step_names:
            return f"await self.{call.name}({args_str})"

        return f"{call.name}({args_str})"

    def gen_pipe(self, pipe: ast.PipeExpr) -> str:
        """Translate |> pipe operator to nested function calls."""
        result = self.gen_expr(pipe.input_expr)
        for op in pipe.operations:
            if isinstance(op, ast.FnCall):
                args = ", ".join(self.gen_expr(a) for a in op.args)
                if args:
                    result = f"{op.name}({result}, {args})"
                else:
                    result = f"{op.name}({result})"
            elif isinstance(op, ast.Ident):
                result = f"{op.name}({result})"
            else:
                result = f"{self.gen_expr(op)}({result})"
        return result

    # ─── Intent Expressions ────────────────────────────────────────

    def gen_intent(self, intent: ast.IntentExpr) -> str:
        """
        Translate intent verbs into runtime calls.
        This is where Drift's magic happens:
            classify doc as Category
        becomes:
            await self.intent(verb="classify", input=doc, output_schema=Category)
        """
        parts = [f'verb="{intent.verb}"']

        # Input
        if intent.input_expr:
            parts.append(f"input_data={self.gen_expr(intent.input_expr)}")

        # Output schema (from 'as' clause)
        if 'as' in intent.clauses:
            type_expr = intent.clauses['as']
            py_type = self.gen_type(type_expr)
            parts.append(f"output_schema={py_type}")

        # Source (from 'from' clause)
        if 'from' in intent.clauses:
            parts.append(f"source={self.gen_expr(intent.clauses['from'])}")

        # Count (from 'in' clause — "in 3 sentences")
        if 'in' in intent.clauses:
            clause = intent.clauses['in']
            if isinstance(clause, dict):
                parts.append(f'count={clause["count"]}')
                parts.append(f'unit="{clause["unit"]}"')
            else:
                parts.append(f"count={self.gen_expr(clause)}")

        # Criteria (from 'against' clause)
        if 'against' in intent.clauses:
            parts.append(f"criteria={self.gen_expr(intent.clauses['against'])}")

        # Target (from 'to' clause)
        if 'to' in intent.clauses:
            parts.append(f"target={self.gen_expr(intent.clauses['to'])}")

        # Context (from 'using' clause)
        if 'using' in intent.clauses:
            parts.append(f"context={self.gen_expr(intent.clauses['using'])}")

        # Factors (from 'considering' clause)
        if 'considering' in intent.clauses:
            factors = intent.clauses['considering']
            factors_str = "[" + ", ".join(self.gen_expr(f) for f in factors) + "]"
            parts.append(f"factors={factors_str}")

        args_str = ", ".join(parts)
        return f"await self.intent({args_str})"
