"""
Auto-generated by Drift v0.1 — do not edit by hand.
Source: examples/confident_demo.drift
"""

import asyncio
from typing import Optional, Literal
from dataclasses import dataclass, field

# Drift runtime imports
from drift.runtime import (
    Agent, step_decorator, Budget, ModelRouter, Intent,
    CostTracker, Checkpoint, Confident, MemoryStore, run_agent,
    make_memory_store, StreamThenRouter,
    register_custom_verb, coerce_arg,
    DriftError, StepFailed, SchemaViolation, BudgetExceeded,
    ModelUnavailable, RateLimited, AuthError,
)

__drift_source__ = "<drift_file>"

# ── Config ──
DRIFT_CONFIG = {
    "name": "Confident Demo",
    "version": "0.1.0",
}

# ── Agent: Triager ──

class Triager(Agent):
    """Drift agent: Triager"""

    def __init__(self):
        model = ModelRouter(default="claude-haiku")
        budget = Budget(max_per_run=0.5, currency="USD")

        super().__init__(
            name="Triager",
            model=model,
            budget=budget,
            min_confidence=0.85,
        )

    @step_decorator(output=str)
    async def triage(self, item: str) -> str:
        # Budget pre-check
        self.cost_tracker.pre_check()

        result = await self.intent(verb="classify", input_data=item, output_schema=Confident[str])
        if (result.is_confident(self.min_confidence)):
            self.output(f"Auto-processed: {result.value} (confidence {result.confidence})")
            _result = result.value
            self.checkpoint.save('triage', _result)
            return _result
        elif (not result.is_confident(self.min_confidence)):
            self.output(f"Flagged for human review: {result.value}")
            _result = "needs_review"
            self.checkpoint.save('triage', _result)
            return _result
