"""
Auto-generated by Drift v0.1 — do not edit by hand.
Source: examples/grant_checker_with_memory.drift
"""

import asyncio
from typing import Optional, Literal
from dataclasses import dataclass, field

# Drift runtime imports
from drift.runtime import (
    Agent, step_decorator, Budget, ModelRouter, Intent,
    CostTracker, Checkpoint, Confident, MemoryStore, run_agent,
    make_memory_store, StreamThenRouter,
    register_custom_verb,
    DriftError, StepFailed, SchemaViolation, BudgetExceeded,
    ModelUnavailable, RateLimited, AuthError,
)

# ── Config ──
DRIFT_CONFIG = {
    "name": "Grant Eligibility Checker (with memory)",
    "version": "1.0.0",
}

# ── Schema: FitScore ──

@dataclass
class FitScore:
    """Drift schema: FitScore"""
    company_name: str
    overall_score: float  # valid range: 0.0 to 100.0
    recommendation: Literal["strong fit", "possible fit", "weak fit", "no fit"]
    reasoning: str
    confidence: float  # valid range: 0.0 to 1.0

    def validate(self):
        """Validate field constraints."""
        if self.overall_score is not None:
            assert 0.0 <= self.overall_score <= 100.0, \
                f"overall_score must be between 0.0 and 100.0, got {self.overall_score}"
        if self.confidence is not None:
            assert 0.0 <= self.confidence <= 1.0, \
                f"confidence must be between 0.0 and 1.0, got {self.confidence}"
        return self

# ── Agent: GrantChecker ──

class GrantChecker(Agent):
    """Drift agent: GrantChecker"""

    def __init__(self):
        model = ModelRouter(default="claude-haiku", fallback=["claude-sonnet"])
        budget = Budget(max_per_run=5.0, currency="GBP")

        super().__init__(
            name="GrantChecker",
            model=model,
            budget=budget,
            min_confidence=0.85,
            memory=make_memory_store(persona='grant_history'),
        )

    @step_decorator(output=FitScore)
    async def evaluate(self, company_profile: str, call_text: str) -> FitScore:
        # Budget pre-check
        self.cost_tracker.pre_check()

        past = self.memory.recall('similar evaluations', key=company_profile)
        score = await self.intent(verb="rate", input_data=company_profile, output_schema=FitScore, criteria=call_text)
        _dv_1 = self.memory.deja_vu_check(context=company_profile)
        if _dv_1 is not None:
            match = _dv_1
            if match.matches('similar_rejection'):
                self.output("Warning: a similar profile was rejected previously")
            elif match.matches('successful_pattern'):
                self.output("Pattern matches a previous successful application")
            else:
                self.output("Novel profile — no archive resonance")
        self.memory.remember(score, tag="healthcare innovate_uk")
        _result = score
        self.checkpoint.save('evaluate', _result)
        return _result

    @step_decorator(output=str)
    async def cleanup(self) -> str:
        # Budget pre-check
        self.cost_tracker.pre_check()

        self.memory.forget(below_temp=0.05)
        _result = "cleaned"
        self.checkpoint.save('cleanup', _result)
        return _result
