"""
Auto-generated by Drift v0.1 — do not edit by hand.
Source: examples/grant_checker_compare.drift
"""

import asyncio
from typing import Optional, Literal
from dataclasses import dataclass, field

# Drift runtime imports
from drift.runtime import (
    Agent, step_decorator, Budget, ModelRouter, Intent,
    CostTracker, Checkpoint, Confident, MemoryStore, run_agent,
    make_memory_store, StreamThenRouter,
    register_custom_verb, coerce_arg,
    DriftError, StepFailed, SchemaViolation, BudgetExceeded,
    ModelUnavailable, RateLimited, AuthError,
)

__drift_source__ = "<drift_file>"

# ── Config ──
DRIFT_CONFIG = {
    "name": "Grant Eligibility Checker (with citation)",
    "version": "1.0.0",
}

# ── Schema: FitScore ──

@dataclass
class FitScore:
    """Drift schema: FitScore"""
    company_name: str
    overall_score: float  # valid range: 0.0 to 100.0
    recommendation: Literal["strong fit", "possible fit", "weak fit", "no fit"]
    reasoning: str
    confidence: float  # valid range: 0.0 to 1.0

    def validate(self):
        """Validate field constraints. Raises SchemaViolation on failure."""
        if self.overall_score is not None and not (0.0 <= self.overall_score <= 100.0):
            raise SchemaViolation(f"overall_score must be between 0.0 and 100.0, got {self.overall_score}")
        if self.confidence is not None and not (0.0 <= self.confidence <= 1.0):
            raise SchemaViolation(f"confidence must be between 0.0 and 1.0, got {self.confidence}")
        if self.recommendation is not None and self.recommendation not in ('strong fit', 'possible fit', 'weak fit', 'no fit'):
            raise SchemaViolation(f"recommendation must be one of 'strong fit', 'possible fit', 'weak fit', 'no fit', got {self.recommendation!r}")
        return self

# ── Custom verb: compare_score ──
register_custom_verb(
    name="compare_score",
    prompt='Score this grant application. CRITICALLY IMPORTANT: prior evaluations of similar companies are provided as CONTEXT. You MUST reference the prior evaluations by company name in your reasoning — explicitly compare the current applicant to them. State whether the current applicant is stronger, weaker, or similar, and why. Return valid JSON matching the schema.',
    output_schema=FitScore,
    pattern='evaluate {target} given prior {context}',
    temperature=0.3,
)

# ── Agent: GrantChecker ──

class GrantChecker(Agent):
    """Drift agent: GrantChecker"""

    def __init__(self):
        model = ModelRouter(default="gpt-5.4")
        budget = Budget(max_per_run=5.0, currency="GBP")

        super().__init__(
            name="GrantChecker",
            model=model,
            budget=budget,
            min_confidence=0.85,
            memory=make_memory_store(persona='grant_history_compare'),
        )

    @step_decorator(output=FitScore)
    async def evaluate(self, company_profile: str, call_text: str) -> FitScore:
        # Budget pre-check
        self.cost_tracker.pre_check()

        past = self.memory.recall('similar evaluations', key=company_profile)
        score = await self.intent(verb="compare_score", input_data=company_profile, output_schema=FitScore, criteria=call_text, context=past)
        self.memory.remember(score, tag="healthcare innovate_uk")
        _result = score
        self.checkpoint.save('evaluate', _result)
        return _result
