"""
Auto-generated by Drift v0.1 — do not edit by hand.
Source: examples/grant_checker.drift
"""

import asyncio
from typing import Optional, Literal
from dataclasses import dataclass, field

# Drift runtime imports
from drift.runtime import (
    Agent, step_decorator, Budget, ModelRouter, Intent,
    CostTracker, Checkpoint, Confident, MemoryStore, run_agent,
    make_memory_store, StreamThenRouter,
    register_custom_verb,
    DriftError, StepFailed, SchemaViolation, BudgetExceeded,
    ModelUnavailable, RateLimited, AuthError,
)

__drift_source__ = "<drift_file>"

# ── Config ──
DRIFT_CONFIG = {
    "name": "Grant Eligibility Checker",
    "version": "1.0.0",
}

# ── Schema: EligibilityCriteria ──

@dataclass
class EligibilityCriteria:
    """Drift schema: EligibilityCriteria"""
    sector_requirements: list[str]
    size_requirements: str
    geographic_scope: str
    technical_focus: list[str]
    funding_range: str

# ── Schema: FitScore ──

@dataclass
class FitScore:
    """Drift schema: FitScore"""
    company_name: str
    grant_title: str
    overall_score: float  # valid range: 0.0 to 100.0
    matching_criteria: list[str]
    gaps: list[str]
    recommendation: Literal["strong fit", "possible fit", "weak fit", "no fit"]
    reasoning: str
    confidence: float  # valid range: 0.0 to 1.0

    def validate(self):
        """Validate field constraints."""
        if self.overall_score is not None:
            assert 0.0 <= self.overall_score <= 100.0, \
                f"overall_score must be between 0.0 and 100.0, got {self.overall_score}"
        if self.confidence is not None:
            assert 0.0 <= self.confidence <= 1.0, \
                f"confidence must be between 0.0 and 1.0, got {self.confidence}"
        return self

# ── Agent: GrantChecker ──

class GrantChecker(Agent):
    """Drift agent: GrantChecker"""

    def __init__(self):
        model = ModelRouter(default="claude-sonnet", fallback=["gpt-4o"])
        budget = Budget(max_per_run=5.0, currency="GBP")

        super().__init__(
            name="GrantChecker",
            model=model,
            budget=budget,
            min_confidence=0.85,
        )

    @step_decorator(output=EligibilityCriteria)
    async def parse_call(self, call_text: str) -> EligibilityCriteria:
        # Budget pre-check
        self.cost_tracker.pre_check()

        _result = await self.intent(verb="extract", input_data=["sector_requirements", "size_requirements", "geographic_scope", "technical_focus", "funding_range"], output_schema=EligibilityCriteria, source=call_text)
        self.checkpoint.save('parse_call', _result)
        return _result

    @step_decorator(output=FitScore)
    async def evaluate(self, company_profile: str, call_text: str) -> FitScore:
        # Budget pre-check
        self.cost_tracker.pre_check()

        criteria = await self.parse_call(call_text)
        score = await self.intent(verb="rate", input_data=company_profile, output_schema=FitScore, criteria=criteria)
        if (score.overall_score > 70):
            self.output(f"Strong match: {score.company_name} scores {score.overall_score}/100")
        elif (score.overall_score > 40):
            self.output(f"Possible match: {score.company_name} — review recommended")
        else:
            self.output(f"Low fit: {score.company_name} — {score.recommendation}")
        _result = score
        self.checkpoint.save('evaluate', _result)
        return _result
