"""
Auto-generated by Drift v0.1 — do not edit by hand.
Source: examples/hello.drift
"""

import asyncio
from typing import Optional, Literal
from dataclasses import dataclass, field

# Drift runtime imports
from drift.runtime import (
    Agent, step_decorator, Budget, ModelRouter, Intent,
    CostTracker, Checkpoint, Confident, MemoryStore, run_agent,
    make_memory_store, StreamThenRouter,
    register_custom_verb, coerce_arg, gather_or_cancel,
    DriftError, StepFailed, SchemaViolation, BudgetExceeded,
    ModelUnavailable, RateLimited, AuthError,
)

__drift_source__ = "<drift_file>"

# ── Config ──
DRIFT_CONFIG = {
    "name": "Hello World",
    "version": "0.1.0",
}

# ── Agent: Greeter ──

class Greeter(Agent):
    """Drift agent: Greeter"""

    def __init__(self):
        model = ModelRouter(default="claude-haiku")
        budget = Budget(max_per_run=0.1, currency="USD")

        super().__init__(
            name="Greeter",
            model=model,
            budget=budget,
            min_confidence=0.85,
        )

    @step_decorator(output=str)
    async def hello(self, name: str) -> str:
        # Budget pre-check
        self.cost_tracker.pre_check()

        greeting = await self.intent(verb="generate", input_data="a warm welcome message", output_schema=str)
        self.output(f"Hello, {name}!")
        _result = greeting
        self.checkpoint.save('hello', _result)
        return _result
