"""
Auto-generated by Drift v0.1 — do not edit by hand.
Source: examples/inbox_triage_live.drift
"""

import asyncio
from typing import Optional, Literal
from dataclasses import dataclass, field

# Drift runtime imports
from drift.runtime import (
    Agent, step_decorator, Budget, ModelRouter, Intent,
    CostTracker, Checkpoint, Confident, MemoryStore, run_agent,
    make_memory_store, StreamThenRouter,
    register_custom_verb,
    DriftError, StepFailed, SchemaViolation, BudgetExceeded,
    ModelUnavailable, RateLimited, AuthError,
)

__drift_source__ = "<drift_file>"

# ── Config ──
DRIFT_CONFIG = {
    "name": "Inbox Triage",
    "version": "0.1.0",
}

# ── Schema: EmailAnalysis ──

@dataclass
class EmailAnalysis:
    """Drift schema: EmailAnalysis"""
    subject: str
    priority: Literal["urgent", "normal", "low"]
    category: Literal["billing", "support", "sales", "spam", "personal"]
    summary: str
    suggested_action: str

# ── Agent: InboxTriage ──

class InboxTriage(Agent):
    """Drift agent: InboxTriage"""

    def __init__(self):
        model = ModelRouter(default="gpt-5.4-nano")
        budget = Budget(max_per_run=0.1, currency="USD")

        super().__init__(
            name="InboxTriage",
            model=model,
            budget=budget,
            min_confidence=0.85,
        )

    @step_decorator(output=list[EmailAnalysis])
    async def triage(self, emails: list[str]) -> list[EmailAnalysis]:
        # Budget pre-check
        self.cost_tracker.pre_check()

        analyses = []
        # Parallel fan-out (concurrent execution)
        async def _task(email):
            analysis = await self.intent(verb="classify", input_data=email, output_schema=EmailAnalysis)
            analyses.append(analysis)
        await asyncio.gather(*[_task(item) for item in emails])
        for a in analyses:
            if (a.priority == "urgent"):
                self.output(f"URGENT — {a.subject}: {a.summary}")
        _result = analyses
        self.checkpoint.save('triage', _result)
        return _result
