"""
Auto-generated by Drift v0.1 — do not edit by hand.
Source: examples/inbox_sorter.drift
"""

import asyncio
from typing import Optional, Literal
from dataclasses import dataclass, field

# Drift runtime imports
from drift.runtime import (
    Agent, step_decorator, Budget, ModelRouter, Intent,
    CostTracker, Checkpoint, Confident, MemoryStore, run_agent,
    make_memory_store, StreamThenRouter,
    register_custom_verb,
    DriftError, StepFailed, SchemaViolation, BudgetExceeded,
    ModelUnavailable, RateLimited, AuthError,
)

__drift_source__ = "<drift_file>"

# ── Config ──
DRIFT_CONFIG = {
    "name": "Inbox Sorter",
    "version": "1.0.0",
}

# ── Schema: EmailAnalysis ──

@dataclass
class EmailAnalysis:
    """Drift schema: EmailAnalysis"""
    subject: str
    priority: Literal["urgent", "normal", "low"]
    category: Literal["work", "personal", "newsletter", "spam"]
    summary: str
    action_needed: bool
    confidence: float  # valid range: 0.0 to 1.0

    def validate(self):
        """Validate field constraints. Raises SchemaViolation on failure."""
        if self.confidence is not None and not (0.0 <= self.confidence <= 1.0):
            raise SchemaViolation(f"confidence must be between 0.0 and 1.0, got {self.confidence}")
        if self.priority is not None and self.priority not in ('urgent', 'normal', 'low'):
            raise SchemaViolation(f"priority must be one of 'urgent', 'normal', 'low', got {self.priority!r}")
        if self.category is not None and self.category not in ('work', 'personal', 'newsletter', 'spam'):
            raise SchemaViolation(f"category must be one of 'work', 'personal', 'newsletter', 'spam', got {self.category!r}")
        return self

# ── Agent: InboxSorter ──

class InboxSorter(Agent):
    """Drift agent: InboxSorter"""

    def __init__(self):
        model = ModelRouter(default="claude-haiku", fallback=["gpt-4o-mini"])
        budget = Budget(max_per_run=0.5, currency="USD")

        super().__init__(
            name="InboxSorter",
            model=model,
            budget=budget,
            min_confidence=0.85,
        )

    @step_decorator(output=list[EmailAnalysis])
    async def sort_emails(self, emails: list[str]) -> list[EmailAnalysis]:
        # Budget pre-check
        self.cost_tracker.pre_check()

        results = []
        for email in emails:
            analysis = await self.intent(verb="classify", input_data=email, output_schema=EmailAnalysis)
            if (analysis.priority == "urgent"):
                self.output(f"URGENT: {analysis.subject} — {analysis.summary}")
            results.append(analysis)
        _result = results
        self.checkpoint.save('sort_emails', _result)
        return _result
