"""
Auto-generated by Drift v0.1 — do not edit by hand.
Source: examples/apps/candidate_schemas.drift
"""

import asyncio
from typing import Optional, Literal
from dataclasses import dataclass, field

# Drift runtime imports
from drift.runtime import (
    Agent, step_decorator, Budget, ModelRouter, Intent,
    CostTracker, Checkpoint, Confident, MemoryStore, run_agent,
    make_memory_store, StreamThenRouter,
    register_custom_verb, coerce_arg,
    DriftError, StepFailed, SchemaViolation, BudgetExceeded,
    ModelUnavailable, RateLimited, AuthError,
)

__drift_source__ = "<drift_file>"

# ── Schema: Candidate ──

@dataclass
class Candidate:
    """Drift schema: Candidate"""
    name: str
    resume_text: str

# ── Schema: CandidateProfile ──

@dataclass
class CandidateProfile:
    """Drift schema: CandidateProfile"""
    years_experience: int
    key_skills: list[str]
    seniority: Literal["junior", "mid", "senior", "staff"]

    def validate(self):
        """Validate field constraints. Raises SchemaViolation on failure."""
        if self.seniority is not None and self.seniority not in ('junior', 'mid', 'senior', 'staff'):
            raise SchemaViolation(f"seniority must be one of 'junior', 'mid', 'senior', 'staff', got {self.seniority!r}")
        return self

# ── Schema: FitDecision ──

@dataclass
class FitDecision:
    """Drift schema: FitDecision"""
    recommend: bool
    reasoning: str
