"""
Auto-generated by Drift v0.1 — do not edit by hand.
Source: examples/apps/content_moderator.drift
"""

import asyncio
from typing import Optional, Literal
from dataclasses import dataclass, field

# Drift runtime imports
from drift.runtime import (
    Agent, step_decorator, Budget, ModelRouter, Intent,
    CostTracker, Checkpoint, Confident, MemoryStore, run_agent,
    make_memory_store, StreamThenRouter,
    register_custom_verb, coerce_arg,
    DriftError, StepFailed, SchemaViolation, BudgetExceeded,
    ModelUnavailable, RateLimited, AuthError,
)

__drift_source__ = "<drift_file>"

from drift.safety import redact_pii, check_content, rate_limit

# ── Config ──
DRIFT_CONFIG = {
    "name": "Content Moderator",
    "version": "0.1.0",
}

# ── Schema: ModerationResult ──

@dataclass
class ModerationResult:
    """Drift schema: ModerationResult"""
    verdict: Literal["approved", "needs_review", "rejected"]
    reason: str

    def validate(self):
        """Validate field constraints. Raises SchemaViolation on failure."""
        if self.verdict is not None and self.verdict not in ('approved', 'needs_review', 'rejected'):
            raise SchemaViolation(f"verdict must be one of 'approved', 'needs_review', 'rejected', got {self.verdict!r}")
        return self

# ── Agent: Moderator ──

class Moderator(Agent):
    """Drift agent: Moderator"""

    def __init__(self):
        model = ModelRouter(default="claude-haiku", fallback=["gpt-4o-mini"], upgrades=[{"target": "claude-sonnet", "conditions": [{"kind": "confidence_lt", "value": 0.7}]}])
        budget = Budget(max_per_run=0.1, currency="USD")

        super().__init__(
            name="Moderator",
            model=model,
            budget=budget,
            min_confidence=0.7,
        )

    @step_decorator(output=str)
    async def moderate(self, user_id: str, content: str) -> str:
        # Budget pre-check
        self.cost_tracker.pre_check()

        allowed = rate_limit(user_id, max_per_window=10, window_seconds=60)
        if not allowed:
            raise StepFailed("rate limit exceeded — try again shortly")
        clean = redact_pii(content)
        is_clean = check_content(clean, banned_patterns=["spam", "scam"])
        if not is_clean:
            self.output("Rejected: matched a banned pattern")
            _result = "rejected"
            self.checkpoint.save('moderate', _result)
            return _result
        result = await self.intent(verb="classify", input_data=clean, output_schema=Confident[ModerationResult])
        if (result.is_confident(self.min_confidence)):
            self.output(f"Moderation verdict: {result.value.verdict} — {result.value.reason}")
            _result = result.value.verdict
            self.checkpoint.save('moderate', _result)
            return _result
        else:
            self.output(f"Low confidence — routing {user_id}'s submission to human review")
            _result = "needs_review"
            self.checkpoint.save('moderate', _result)
            return _result
