"""
Auto-generated by Drift v0.1 — do not edit by hand.
Source: examples/apps/lead_qualifier.drift
"""

import asyncio
from typing import Optional, Literal
from dataclasses import dataclass, field

# Drift runtime imports
from drift.runtime import (
    Agent, step_decorator, Budget, ModelRouter, Intent,
    CostTracker, Checkpoint, Confident, MemoryStore, run_agent,
    make_memory_store, StreamThenRouter,
    register_custom_verb, coerce_arg,
    DriftError, StepFailed, SchemaViolation, BudgetExceeded,
    ModelUnavailable, RateLimited, AuthError,
)

__drift_source__ = "<drift_file>"

# ── Config ──
DRIFT_CONFIG = {
    "name": "Lead Qualifier",
    "version": "0.1.0",
}

# ── Schema: Lead ──

@dataclass
class Lead:
    """Drift schema: Lead"""
    company_name: str
    industry: str
    employee_count: int
    use_case: str

# ── Schema: LeadScore ──

@dataclass
class LeadScore:
    """Drift schema: LeadScore"""
    fit: Literal["strong fit", "possible fit", "weak fit", "no fit"]
    reasoning: str
    suggested_outreach_angle: str

    def validate(self):
        """Validate field constraints. Raises SchemaViolation on failure."""
        if self.fit is not None and self.fit not in ('strong fit', 'possible fit', 'weak fit', 'no fit'):
            raise SchemaViolation(f"fit must be one of 'strong fit', 'possible fit', 'weak fit', 'no fit', got {self.fit!r}")
        return self

# ── Agent: LeadQualifier ──

class LeadQualifier(Agent):
    """Drift agent: LeadQualifier"""

    def __init__(self):
        model = ModelRouter(default="claude-sonnet", fallback=["gpt-4o-mini"])
        budget = Budget(max_per_run=0.15, currency="USD")

        super().__init__(
            name="LeadQualifier",
            model=model,
            budget=budget,
            min_confidence=0.75,
            memory=make_memory_store(persona='sales_leads'),
        )

    @step_decorator(output=LeadScore)
    async def qualify(self, lead: Lead) -> LeadScore:
        # Budget pre-check
        self.cost_tracker.pre_check()

        past_context = self.memory.recall(f"leads similar to {lead.company_name} in {lead.industry}", key="qualification")
        scored = await self.intent(verb="rate", input_data=lead, output_schema=Confident[LeadScore], criteria="ICP fit: mid-market to enterprise B2B SaaS companies with a clear automation use case, considering past_context")
        if (scored.is_confident(self.min_confidence)):
            self.output(f"Qualified {lead.company_name}: {scored.value.fit}")
            self.memory.remember(f"{lead.company_name} ({lead.industry}, {lead.employee_count} employees): {scored.value.fit} — {scored.value.reasoning}", tag=["qualification", lead.industry])
            if ((scored.value.fit == "strong fit") or (scored.value.fit == "possible fit")):
                outreach = await self.intent(verb="generate", input_data="a short personalized outreach email opening line", output_schema=str, context=[scored.value.suggested_outreach_angle, lead.company_name])
                self.output(f"Outreach angle: {outreach}")
            _result = scored.value
            self.checkpoint.save('qualify', _result)
            return _result
        else:
            self.output(f"Low confidence on {lead.company_name} — flagging for human review")
            self.memory.remember(f"{lead.company_name}: low-confidence result, needs human review", tag=["needs-review", lead.industry])
            raise StepFailed("confidence below threshold — needs human review")
