"""
Auto-generated by Drift v0.1 — do not edit by hand.
Source: examples/apps/resume_screener.drift
"""

import asyncio
from typing import Optional, Literal
from dataclasses import dataclass, field

# Drift runtime imports
from drift.runtime import (
    Agent, step_decorator, Budget, ModelRouter, Intent,
    CostTracker, Checkpoint, Confident, MemoryStore, run_agent,
    make_memory_store, StreamThenRouter,
    register_custom_verb, coerce_arg,
    DriftError, StepFailed, SchemaViolation, BudgetExceeded,
    ModelUnavailable, RateLimited, AuthError,
)

__drift_source__ = "<drift_file>"

from candidate_schemas import Candidate, CandidateProfile, FitDecision

# ── Config ──
DRIFT_CONFIG = {
    "name": "Resume Screener",
    "version": "0.1.0",
}

# ── Agent: Screener ──

class Screener(Agent):
    """Drift agent: Screener"""

    def __init__(self):
        model = ModelRouter(default="claude-haiku")
        budget = Budget(max_per_run=0.2, currency="USD")

        super().__init__(
            name="Screener",
            model=model,
            budget=budget,
            min_confidence=0.85,
        )

    @step_decorator(output=list[CandidateProfile])
    async def profile_candidates(self, candidates: list[Candidate]) -> list[CandidateProfile]:
        # Budget pre-check
        self.cost_tracker.pre_check()

        profiles = []
        # Parallel fan-out (concurrent execution)
        async def _task(candidate):
            profile = await self.intent(verb="extract", input_data=["years_experience", "key_skills", "seniority"], output_schema=CandidateProfile, source=candidate.resume_text)
            profiles.append(profile)
        await asyncio.gather(*[_task(item) for item in candidates])
        _result = profiles
        self.checkpoint.save('profile_candidates', _result)
        return _result

    @step_decorator(output=FitDecision)
    async def decide_fit(self, profile: CandidateProfile, job_spec: str) -> FitDecision:
        # Budget pre-check
        self.cost_tracker.pre_check()

        decision = await self.intent(verb="decide", input_data=profile, output_schema=FitDecision, criteria=job_spec)
        _result = decision
        self.checkpoint.save('decide_fit', _result)
        return _result
