"""
Auto-generated by Drift v0.1 — do not edit by hand.
Source: examples/apps/support_escalation.drift
"""

import asyncio
from typing import Optional, Literal
from dataclasses import dataclass, field

# Drift runtime imports
from drift.runtime import (
    Agent, step_decorator, Budget, ModelRouter, Intent,
    CostTracker, Checkpoint, Confident, MemoryStore, run_agent,
    make_memory_store, StreamThenRouter,
    register_custom_verb, coerce_arg,
    DriftError, StepFailed, SchemaViolation, BudgetExceeded,
    ModelUnavailable, RateLimited, AuthError,
)

__drift_source__ = "<drift_file>"

# ── Config ──
DRIFT_CONFIG = {
    "name": "Support Escalation Router",
    "version": "0.1.0",
}

# ── Schema: Urgency ──

@dataclass
class Urgency:
    """Drift schema: Urgency"""
    level: Literal["low", "medium", "high", "critical"]
    reason: str

    def validate(self):
        """Validate field constraints. Raises SchemaViolation on failure."""
        if self.level is not None and self.level not in ('low', 'medium', 'high', 'critical'):
            raise SchemaViolation(f"level must be one of 'low', 'medium', 'high', 'critical', got {self.level!r}")
        return self

# ── Custom verb: triage_urgency ──
register_custom_verb(
    name="triage_urgency",
    prompt='You are a support triage specialist. Assess how urgently this customer message needs a human response.',
    output_schema=Urgency,
    pattern='',
    temperature=0.1,
)

# ── Agent: Notifier ──

class Notifier(Agent):
    """Drift agent: Notifier"""

    def __init__(self):
        model = ModelRouter(default="claude-haiku")
        budget = Budget(max_per_run=0.02, currency="USD")

        super().__init__(
            name="Notifier",
            model=model,
            budget=budget,
            min_confidence=0.85,
        )

    @step_decorator(output=str)
    async def alert_oncall(self, message: str, reason: str) -> str:
        # Budget pre-check
        self.cost_tracker.pre_check()

        self.output(f"PAGING ONCALL: {reason} — {message}")
        _result = "paged"
        self.checkpoint.save('alert_oncall', _result)
        return _result

# ── Agent: EscalationRouter ──

class EscalationRouter(Agent):
    """Drift agent: EscalationRouter"""

    def __init__(self):
        model = ModelRouter(default="claude-haiku", fallback=["gpt-4o-mini"])
        budget = Budget(max_per_run=0.1, currency="USD")

        super().__init__(
            name="EscalationRouter",
            model=model,
            budget=budget,
            min_confidence=0.85,
        )

        # Agent state (persists across steps within a run)
        self.escalation_count = 0

    @step_decorator(output=str)
    async def route(self, message: str) -> str:
        # Budget pre-check
        self.cost_tracker.pre_check()

        # attempt/recover (max 3 retries)
        for _attempt in range(3):
            try:
                urgency = await self.intent(verb="triage_urgency", input_data=message, output_schema=Urgency)
                if urgency.level == "critical":
                    self.escalation_count = (self.escalation_count + 1)
                    await Notifier().alert_oncall(message, urgency.reason)
                    self.output(f"Routed as CRITICAL ({self.escalation_count} escalations this run)")
                    _result = "critical"
                    self.checkpoint.save('route', _result)
                    return _result
                elif urgency.level == "high":
                    self.escalation_count = (self.escalation_count + 1)
                    self.output(f"Routed as HIGH priority: {urgency.reason}")
                    _result = "high"
                    self.checkpoint.save('route', _result)
                    return _result
                elif urgency.level == "medium":
                    self.output(f"Routed as MEDIUM priority: {urgency.reason}")
                    _result = "medium"
                    self.checkpoint.save('route', _result)
                    return _result
                else:
                    self.output(f"Routed as LOW priority: {urgency.reason}")
                    _result = "low"
                    self.checkpoint.save('route', _result)
                    return _result
                break
            except RateLimited as _err:
                continue  # retry the attempt block
            except Exception as _err:
                self.output("Triage failed, defaulting to medium priority for human review")
                _result = "medium"
                self.checkpoint.save('route', _result)
                return _result
        else:
            raise StepFailed("attempt block exhausted 3 retries")
