"""
Auto-generated by Drift v0.1 — do not edit by hand.
Source: examples/apps/ticket_triage.drift
"""

import asyncio
from typing import Optional, Literal
from dataclasses import dataclass, field

# Drift runtime imports
from drift.runtime import (
    Agent, step_decorator, Budget, ModelRouter, Intent,
    CostTracker, Checkpoint, Confident, MemoryStore, run_agent,
    make_memory_store, StreamThenRouter,
    register_custom_verb, coerce_arg,
    DriftError, StepFailed, SchemaViolation, BudgetExceeded,
    ModelUnavailable, RateLimited, AuthError,
)

__drift_source__ = "<drift_file>"

# ── Config ──
DRIFT_CONFIG = {
    "name": "Ticket Triage",
    "version": "0.1.0",
}

# ── Schema: Ticket ──

@dataclass
class Ticket:
    """Drift schema: Ticket"""
    ticket_id: str
    ticket_text: str

# ── Schema: TicketAnalysis ──

@dataclass
class TicketAnalysis:
    """Drift schema: TicketAnalysis"""
    category: Literal["billing", "technical", "account", "general"]
    urgency: Literal["low", "medium", "high", "critical"]
    summary: str
    confidence: float  # valid range: 0.0 to 1.0

    def validate(self):
        """Validate field constraints. Raises SchemaViolation on failure."""
        if self.confidence is not None and not (0.0 <= self.confidence <= 1.0):
            raise SchemaViolation(f"confidence must be between 0.0 and 1.0, got {self.confidence}")
        if self.category is not None and self.category not in ('billing', 'technical', 'account', 'general'):
            raise SchemaViolation(f"category must be one of 'billing', 'technical', 'account', 'general', got {self.category!r}")
        if self.urgency is not None and self.urgency not in ('low', 'medium', 'high', 'critical'):
            raise SchemaViolation(f"urgency must be one of 'low', 'medium', 'high', 'critical', got {self.urgency!r}")
        return self

# ── Schema: Outcome ──

@dataclass
class Outcome:
    """Drift schema: Outcome"""
    ticket_id: str
    category: str
    urgency: str
    action: Literal["responded", "escalated"]
    detail: str

    def validate(self):
        """Validate field constraints. Raises SchemaViolation on failure."""
        if self.action is not None and self.action not in ('responded', 'escalated'):
            raise SchemaViolation(f"action must be one of 'responded', 'escalated', got {self.action!r}")
        return self

# ── Tool: helpdesk (rest) ──
class _helpdesk_RestTool:
    """REST tool adapter generated from a `tool` block."""
    endpoint = 'https://helpdesk.example.com/api'
    auth_env = 'HELPDESK_TOKEN'
    auth_literal = None

    def _auth_header(self):
        import os
        if self.auth_literal:
            return {"Authorization": f"Bearer {self.auth_literal}"}
        if not self.auth_env: return {}
        token = os.environ.get(self.auth_env)
        return {"Authorization": f"Bearer {token}"} if token else {}

    async def post_outcome(self, ticket_id: str, action: str, detail: str):
        """POST /tickets/{ticket_id}/outcome"""
        import httpx
        path = f'/tickets/{ticket_id}/outcome'
        url = self.endpoint + path
        _body = {'action': action, 'detail': detail}
        async with httpx.AsyncClient() as client:
            resp = await client.post(url, headers=self._auth_header(), timeout=30.0, json=_body)
        resp.raise_for_status()
        return resp.json()
helpdesk = _helpdesk_RestTool()

# ── Agent: Intake ──

class Intake(Agent):
    """Drift agent: Intake"""

    def __init__(self):
        model = ModelRouter(default="claude-haiku")
        budget = Budget(max_per_run=0.01, currency="USD")

        super().__init__(
            name="Intake",
            model=model,
            budget=budget,
            min_confidence=0.85,
        )

    @step_decorator(output=list[Ticket])
    async def tickets(self, batch: list[Ticket]) -> list[Ticket]:
        # Budget pre-check
        self.cost_tracker.pre_check()

        _result = batch
        self.checkpoint.save('tickets', _result)
        return _result

# ── Agent: Responder ──

class Responder(Agent):
    """Drift agent: Responder"""

    def __init__(self):
        model = ModelRouter(default="claude-haiku", fallback=["gpt-4o-mini"])
        budget = Budget(max_per_run=0.1, currency="USD")

        super().__init__(
            name="Responder",
            model=model,
            budget=budget,
            min_confidence=0.75,
        )

    @step_decorator(output=str)
    async def draft_reply(self, ticket_text: str, category: str) -> str:
        # Budget pre-check
        self.cost_tracker.pre_check()

        reply = await self.intent(verb="generate", input_data="a helpful reply to this support ticket", output_schema=str, factors=[category])
        _result = reply
        self.checkpoint.save('draft_reply', _result)
        return _result

# ── Agent: Router ──

class Router(Agent):
    """Drift agent: Router"""

    def __init__(self):
        model = ModelRouter(default="claude-haiku")
        budget = Budget(max_per_run=0.05, currency="USD")

        super().__init__(
            name="Router",
            model=model,
            budget=budget,
            min_confidence=0.85,
        )

    @step_decorator(output=Outcome)
    async def route(self, ticket: Ticket) -> Outcome:
        # Budget pre-check
        self.cost_tracker.pre_check()

        scored = await self.intent(verb="rate", input_data=ticket.ticket_text, output_schema=Confident[TicketAnalysis], criteria="urgency and category fit")
        if (scored.is_confident(self.min_confidence)):
            reply = await Responder().draft_reply(ticket.ticket_text, scored.value.category)
            self.output(f"Ticket {ticket.ticket_id}: responded ({scored.value.category}/{scored.value.urgency})")
            # attempt/recover (max 3 retries)
            for _attempt in range(3):
                try:
                    await helpdesk.post_outcome(ticket_id=ticket.ticket_id, action="responded", detail=reply)
                    break
                except Exception as _err:
                    self.output(f"helpdesk post failed for {ticket.ticket_id}, continuing anyway")
                    break
            else:
                raise StepFailed("attempt block exhausted 3 retries")
            _result = Outcome(ticket_id=ticket.ticket_id, category=scored.value.category, urgency=scored.value.urgency, action="responded", detail=reply)
            self.checkpoint.save('route', _result)
            return _result
        else:
            self.output(f"Ticket {ticket.ticket_id}: escalated (low confidence)")
            # attempt/recover (max 3 retries)
            for _attempt in range(3):
                try:
                    await helpdesk.post_outcome(ticket_id=ticket.ticket_id, action="escalated", detail="needs human review")
                    break
                except Exception as _err:
                    self.output(f"helpdesk post failed for {ticket.ticket_id}, continuing anyway")
                    break
            else:
                raise StepFailed("attempt block exhausted 3 retries")
            _result = Outcome(ticket_id=ticket.ticket_id, category=scored.value.category, urgency=scored.value.urgency, action="escalated", detail="needs human review")
            self.checkpoint.save('route', _result)
            return _result

# ── Pipeline: Triage ──

class Triage:
    """Drift pipeline: Triage"""

    def __init__(self):
        self.Intake = Intake()
        self.Responder = Responder()
        self.Router = Router()
        self.budget = None
        self.timeout_seconds = 60.0

    async def run(self, initial_input=None):
        """Execute the pipeline. Returns the last node's output."""
        return await asyncio.wait_for(self._orchestrate(initial_input), timeout=60.0)

    async def _orchestrate(self, initial_input=None):
        results = {}
        _prev = initial_input
        # entry node — call signature-checked at runtime
        _prev = await self._call_node(self.Intake.tickets, _prev)
        results['tickets'] = _prev
        # parallel fan-out into Router.route
        _prev = await asyncio.gather(*[self.Router.route(coerce_arg(self.Router.route, item)) for item in _prev])
        results['Router.route'] = _prev
        return _prev

    async def _call_node(self, fn, prev):
        """Call a step. Pass prev only if the signature accepts it."""
        import inspect
        sig = inspect.signature(fn)
        non_self = [p for p in sig.parameters.values() if p.kind != inspect.Parameter.VAR_KEYWORD]
        if non_self:
            return await fn(coerce_arg(fn, prev))
        return await fn()
