"""
Auto-generated by Drift v0.1 — do not edit by hand.
Source: examples/apps/travel_advisor.drift
"""

import asyncio
from typing import Optional, Literal
from dataclasses import dataclass, field

# Drift runtime imports
from drift.runtime import (
    Agent, step_decorator, Budget, ModelRouter, Intent,
    CostTracker, Checkpoint, Confident, MemoryStore, run_agent,
    make_memory_store, StreamThenRouter,
    register_custom_verb, coerce_arg,
    DriftError, StepFailed, SchemaViolation, BudgetExceeded,
    ModelUnavailable, RateLimited, AuthError,
)

__drift_source__ = "<drift_file>"

# ── Config ──
DRIFT_CONFIG = {
    "name": "Travel Advisor",
    "version": "0.1.0",
}

# ── Schema: Destination ──

@dataclass
class Destination:
    """Drift schema: Destination"""
    city: str
    notes: str

# ── Schema: Comparison ──

@dataclass
class Comparison:
    """Drift schema: Comparison"""
    better_choice: str
    reasoning: str

# ── Tool: weather_api (rest) ──
class _weather_api_RestTool:
    """REST tool adapter generated from a `tool` block."""
    endpoint = 'https://api.example.com/weather'
    auth_env = 'WEATHER_API_KEY'
    auth_literal = None

    def _auth_header(self):
        import os
        if self.auth_literal:
            return {"Authorization": f"Bearer {self.auth_literal}"}
        if not self.auth_env: return {}
        token = os.environ.get(self.auth_env)
        return {"Authorization": f"Bearer {token}"} if token else {}

    async def current(self, city: str, units: str):
        """GET /current"""
        import httpx
        path = f'/current'
        url = self.endpoint + path
        _query = {'city': city, 'units': units}
        async with httpx.AsyncClient() as client:
            resp = await client.get(url, headers=self._auth_header(), timeout=30.0, params=_query)
        resp.raise_for_status()
        return resp.json()
weather_api = _weather_api_RestTool()

# ── Agent: TravelAdvisor ──

class TravelAdvisor(Agent):
    """Drift agent: TravelAdvisor"""

    def __init__(self):
        model = ModelRouter(default="claude-haiku", fallback=["gpt-4o-mini"])
        budget = Budget(max_per_run=0.15, currency="USD")

        super().__init__(
            name="TravelAdvisor",
            model=model,
            budget=budget,
            min_confidence=0.85,
            memory=make_memory_store(persona='travel_advice'),
        )

    @step_decorator(output=str)
    async def recommend(self, a: Destination, b: Destination, language: str) -> str:
        # Budget pre-check
        self.cost_tracker.pre_check()

        # attempt/recover (max 3 retries)
        for _attempt in range(3):
            try:
                comparison = await self.intent(verb="compare", input_data=a, output_schema=Comparison, criteria=b)
                advice = f"Go with {comparison.better_choice}: {comparison.reasoning}"
                translated = await self.intent(verb="translate", input_data=advice, output_schema=str, target=language)
                self.memory.remember(translated, tag=["advice", a.city, b.city])
                self.memory.forget(older_than_days=30)
                self.output(f"Recommendation: {translated}")
                _result = translated
                self.checkpoint.save('recommend', _result)
                return _result
            except RateLimited as _err:
                continue  # retry the attempt block
            except Exception as _err:
                self.output("Comparison failed, falling back to a simple recommendation")
                _result = "Consider both options and check current conditions before deciding."
                self.checkpoint.save('recommend', _result)
                return _result
        else:
            raise StepFailed("attempt block exhausted 3 retries")

    @step_decorator(output=dict)
    async def check_conditions(self, city: str) -> dict:
        # Budget pre-check
        self.cost_tracker.pre_check()

        conditions = await weather_api.current(city=city, units="metric")
        _result = conditions
        self.checkpoint.save('check_conditions', _result)
        return _result
